modLoader="javafml"
loaderVersion="[27,)"
issueTrackerURL="https://github.com/MC-U-Team/Useful-Backpacks/issues"
displayURL="https://u-team.info/mods/usefulbackpacks"
logoFile="logo.png"
credits="Team U-Team"
authors="HyCraftHD"

[[mods]]
	modId="usefulbackpacks"
	version="${file.jarVersion}"
	displayName="Useful Backpacks"
	updateJSONURL="https://api.u-team.info/update/usefulbackpacks.json"
	description="This mod adds cool new backpacks to your game."
	
	[[dependencies.usefulbackpacks]]
	    modId="forge"
	    mandatory=true
	    versionRange="[27.0.60,)"
	    ordering="NONE"
	    side="BOTH"
	
	[[dependencies.usefulbackpacks]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.14.3]"
	    ordering="NONE"
	    side="BOTH"
	    
	[[dependencies.usefulbackpacks]]
	    modId="uteamcore"
	    mandatory=true
	    versionRange="[2.5.5.119,)"
	    ordering="NONE"
	    side="BOTH"